# frozen_string_literal: true

require "tmpdir"
require "fileutils"

RSpec.describe ClaudeMemory::Publish, "observations snapshot" do
  let(:tmpdir) { Dir.mktmpdir("publish_obs_#{Process.pid}") }
  let(:store) { ClaudeMemory::Store::SQLiteStore.new(File.join(tmpdir, "memory.sqlite3")) }
  let(:rules_dir) { File.join(tmpdir, ".claude", "rules") }
  let(:publisher) { described_class.new(store) }
  let(:obs_path) { File.join(rules_dir, described_class::OBSERVATIONS_FILE) }

  before { FileUtils.mkdir_p(rules_dir) }

  after do
    store.close
    FileUtils.rm_rf(tmpdir)
  end

  it "reports :empty and writes nothing when there are no observations" do
    result = publisher.publish_observations!(mode: :shared, rules_dir: rules_dir)
    expect(result[:status]).to eq(:empty)
    expect(File.exist?(obs_path)).to be false
  end

  it "writes the observation log with the auto-generated header" do
    store.insert_observation(body: "decided to ship", priority: 1, observed_at: "2026-06-16T00:00:00Z")

    result = publisher.publish_observations!(mode: :shared, rules_dir: rules_dir)

    expect(result[:status]).to eq(:updated)
    content = File.read(obs_path)
    expect(content).to include("auto-generated by claude-memory")
    expect(content).to include("## Project Observations")
    expect(content).to include("- 🔴 decided to ship")
  end

  it "is idempotent — unchanged body is not rewritten" do
    store.insert_observation(body: "stable note", priority: 2)
    publisher.publish_observations!(mode: :shared, rules_dir: rules_dir)

    second = described_class.new(store).publish_observations!(mode: :shared, rules_dir: rules_dir)
    expect(second[:status]).to eq(:unchanged)
  end

  it "publish! also emits the observations sibling file" do
    store.insert_observation(body: "from full publish", priority: 1)
    publisher.publish!(mode: :shared, rules_dir: rules_dir)
    expect(File.exist?(obs_path)).to be true
    expect(File.read(obs_path)).to include("from full publish")
  end
end
